server:
  port: 8888
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848  # 保持与服务一致的Nacos地址
    gateway:
      server:  # server.webflux层级
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user_service_route
              uri: lb://user-service-wxl
              predicates:
                - Path=/api/user/**,/api/auth/**
            - id: qa_service_route
              uri: lb://qa-service-wxl
              predicates:
                - Path=/api/qa/**
# 暴露健康检查端点
management:
  endpoints:
    web:
      exposure:
        include: health,info

# JWT配置（与user-service保持一致）
app:
  jwtSecret: ThisIsASecretKeyForJWTAuthenticationWithEnoughLengthToMeetSecurityRequirements123456
  jwtExpirationMs: 86400000
logging:
  file:
    path: ./logs/api-gateway