server:
  port: 9999
spring:
  application:
    name: user-service-wxl
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/ai_qa_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 811024
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
app:
  jwtSecret: ThisIsASecretKeyForJWTAuthenticationWithEnoughLengthToMeetSecurityRequirements123456
  jwtExpirationMs: 86400000
logging:
  file:
    path: ./logs/user-service